services:
  sqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Pass123**'
      MSSQL_PID: 'Developer'
    ports:
      - "1434:1433"
    volumes:
      - jwt_ecommerce:/var/opt/mssql

volumes:
  jwt_ecommerce:

    #? Recordar tener Docker instalado y en ejecución para usar este archivo docker-compose.yaml.
    #? en el apartdo ports: 1434:1433, el puerto 1434 es el puerto del host (nuestro equipo) y el puerto 1433 es el puerto del contenedor (sqlserver2022). Esto significa que cuando accedamos a localhost:1434 en nuestro equipo, estaremos accediendo al puerto 1433 dentro del contenedor, donde se está ejecutando SQL Server.

    #* Comandos útiles:
    # Levantar los contenedores en segundo plano:
    #*   docker-compose up -d
    # Apagar y eliminar contenedores (no borra los volúmenes):
    #*   docker-compose down
    # detener un contenedor específico:
    #*   docker stop sqlserver2022
    # eliminar un contenedor específico:
    #*   docker rm sqlserver2022



